pipeline:
  build:
    when:
      event: [tag, push, pull_request]
    image: node:${NODE_VERSION}
    commands:
      - npm install

  test:
    when:
      event: [tag, push, pull_request]
    image: node:${NODE_VERSION}
    commands:
      - npm test

  report:
    when:
      status: success
      matrix:
        NODE_VERSION: 6
    image: node:${NODE_VERSION}
    commands:
      - npm install -g coveralls
      - export COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}
      - export COVERALLS_SERVICE_NAME=${CI}
      - export COVERALLS_GIT_COMMIT=${DRONE_COMMIT_SHA}
      - npm run coveralls
  publish:
    when:
      status: success
      event: tag
    commands:
      - npm run compile

matrix:
  NODE_VERSION:
    - 6
    - 7